name: Linter

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - kevins-branch
  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  pull_request:
    branches:
      - kevins-branch
      
permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Install your linters here

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
