name: ESLint workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: browser-actions/setup-chrome@latest
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install modules
      run: npm ci
    - name: Run Nighwatch
      run: npm run test
