name: CI
on:
  push:
    branches:
      - martin22.02.22

  pull_request:
    branches:
      - martin22.02.22
      
permissions:
  checks: write
  contents: write
  
jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out the repository
        uses: actions/checkout@v1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install your dependencies
        run: npm ci

      - name: Run ESLint
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          auto_fix: true
