name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.1
      
      
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
